version = 0.1
[default.deploy.parameters]
stack_name = "sam2-app"
resolve_s3 = true
s3_prefix = "sam2-app"
region = "us-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []

[envtrevor.deploy.parameters]
stack_name = "sam3-app"
resolve_s3 = true
s3_prefix = "sam3-app"
region = "us-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
